resolver: nightly-2020-12-06
packages:
- .
extra-deps:
- compact-0.2.0.0
- ghc-clippy-plugin-0.0.0.1
- polysemy-plugin-0.2.5.1
- subtitleParser-0.5
- replace-megaparsec-1.4.3.0
- path-dhall-instance-0.2.0.0
- path-utils-0.1.1.0
- unliftio-path-0.0.2.0
- polysemy-video-0.1.2.0
- polysemy-http-0.3.0.0
- polysemy-zoo-0.7.0.1
- co-log-polysemy-0.0.1.2
- co-log-polysemy-formatting-0.1.0.0
- polysemy-methodology-0.1.7.0
- polysemy-fskvstore-0.1.0.0
- polysemy-path-0.0.1.0
- polysemy-extra-0.1.5.0
- polysemy-fs-0.1.0.0
- polysemy-vinyl-0.1.4.0
- techlab-0.1.0.0
- formatting-7.1.1
- polysemy-1.4.0.0
- Cabal-3.0.2.0
- polysemy-methodology-composite-0.1.4.0
- chassis-0.0.1.0
allow-newer: true
nix:
  packages: [zlib, libffi, icu]
