resolver: nightly-2020-10-19
packages:
- .
extra-deps:
- compact-0.2.0.0
- polysemy-plugin-0.2.5.1
- subtitleParser-0.5
- replace-megaparsec-1.4.3.0
- path-dhall-instance-0.2.0.0
- path-utils-0.1.1.0
- unliftio-path-0.0.2.0
- polysemy-video-0.1.2.0
- polysemy-zoo-0.7.0.1
- co-log-polysemy-formatting-0.1.0.0
- polysemy-methodology-0.1.3.2
- polysemy-fskvstore-0.1.0.0
- polysemy-path-0.0.1.0
- polysemy-extra-0.1.0.0
- polysemy-fs-0.1.0.0
- formatting-7.1.1@sha256:b7fb414905967e9a7c4230d7a36aa85844cc50da54ae4618b6e0f123901cfa79,3185
nix:
  packages: [zlib, libffi, ffmpeg, pkg-config, icu]
